version: "3.6"

services:
  booklet_backend:
    image: booklet/backend:latest
    build:
      context: .
    command: yarn run watch
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    stdin_open: true
    tty: true